# Generated by Django 4.2.7 on 2023-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('tg_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tg_user_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('tg_user_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('tg_user_username', models.CharField(blank=True, max_length=30, null=True)),
                ('tg_user_language', models.CharField(blank=True, max_length=5, null=True)),
                ('tg_user_registration_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('have_a_subscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.IntegerField()),
                ('tg_user_username', models.CharField(blank=True, max_length=30, null=True)),
                ('tg_handler_name', models.CharField(max_length=60, verbose_name='Название активности в telegram')),
                ('activity_time', models.DateTimeField(auto_now_add=True, verbose_name='Время актиновсти в telegram')),
            ],
        ),
    ]
